### ISSUE TITLE
TypeError: Cannot read property 'jscs' of undefined

### ISSUE THREAD

**Issue by karneaud** [Neofonie/jsc-loader#2]
Trying to run a gulp production command in my project and got the following

> ERROR in ./src/_js/script.js
> Module build failed (from ./node_modules/jscs-loader/index.js):
> TypeError: Cannot read property 'jscs' of undefined
>     at Object.checkSource (/usr/src/app/node_modules/jscs-loader/index.js:70:30)
>     at Object.<anonymous> (/usr/src/app/node_modules/jscs-loader/index.js:140:19)
>     at /usr/src/app/node_modules/jscs-loader/index.js:62:7
>     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
>  @ multi babel-polyfill ./src/_js/script.js main[1]

this is my package.json

```
{
  "name": "harp-babel",
  "version": "0.0.5",
  "description": "A harp boilerplate with babel / es6+",
  "main": "app.js",
  "scripts": {
    "dev": "webpack --progress --colors --watch & gulp",
    "prod": "webpack -p --config webpack.production.config.js & gulp build",
  	"postinstall":"yarn dev"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/glued/harp-babel.git"
  },
  "author": "Richard Worsfold",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/glued/harp-babel/issues"
  },
  "homepage": "https://github.com/glued/harp-babel",
  "dependencies": {
  	"spectre.css":"*",
    "normalize-scss":"*",
    "aos":"*"
  },
  "devDependencies": {
    "babel-core": "*",
  	"babel-cli":"*",
    "babel-eslint": "*",
    "babel-jscs": "*",
  	"babel-preset-env":"*",
    "babel-loader": "*",
    "babel-plugin-transform-remove-console": "*",
    "babel-polyfill": "*",
    "babel-preset-es2015": "*",
    "browser-sync": "*",
    "eslint": "*",
    "eslint-loader": "*",
    "gulp": "*",
    "harp": "*",
    "jscs": "*",
    "jscs-loader": "*",
    "webpack": "*",
    "webpack-cli":"*",
    "uglifyjs-webpack-plugin":"^1.3.0"
  }
}

```

I'm running latest Node/ NPM/ YARN with webpack 4

**Comment by karneaud** [comment]
Please delete this issue. Seems I have the wrong project

**Comment by bitjoo** [comment]
Sorry. This is the wrong repo: jsc-loader. Go to jscs-loader.
